import Head from "next/head";
import { Auth } from "@supabase/auth-ui-react";
import { useRouter } from "next/router";
import { ThemeSupa } from "@supabase/auth-ui-shared";
import {
  useSupabaseClient,
  useSession,
  useUser,
} from "@supabase/auth-helpers-react";
import { Container } from "@mui/material";
import { useEffect } from "react";

export default function Home() {
  const session = useSession();
  const supabase = useSupabaseClient();
  const user = useUser();
  const router = useRouter();

  useEffect(() => {
    if (user) {
      router.push("/profile");
    }
  });

  return (
    <>
      <Head>
        <title>Bookworm - books managament app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container fixed>
        <h1>Bookworm</h1>
        <Container maxWidth="xs">
          {!session ? (
            <Auth
              supabaseClient={supabase}
              appearance={{ theme: ThemeSupa }}
              theme="dark"
              providers={["google"]}
            />
          ) : (
            <p>Loading...</p>
          )}
        </Container>
      </Container>
    </>
  );
}
